# Generated by Django 5.2.7 on 2025-10-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCRMFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dcrm_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.dcrmfile')),
            ],
        ),
    ]
